os: linux
dist: trusty
sudo: required
language: python
python:
  - "2.7"
  - "3.6"

before_install:
  - ./travis/before_install.sh

install:
  - ./travis/install.sh

script:
  - ./travis/script.sh

after_success:
  - ./travis/after_success.sh

after_failure:
  - ./travis/after_failure.sh

cache:
  - directories:
    - $HOME/.cache/pb
    - $HOME/.ccache

branches:
  only:
    - master